// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleBase64():Promise<string>;

export function HandleBase64Decode(arg1:string):Promise<string>;

export function HandleBase64Encode(arg1:string):Promise<string>;

export function HandleGreet():Promise<string>;

export function HandleHome():Promise<string>;
