// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleBase64() {
  return window['go']['main']['App']['HandleBase64']();
}

export function HandleBase64Decode(arg1) {
  return window['go']['main']['App']['HandleBase64Decode'](arg1);
}

export function HandleBase64Encode(arg1) {
  return window['go']['main']['App']['HandleBase64Encode'](arg1);
}

export function HandleGreet() {
  return window['go']['main']['App']['HandleGreet']();
}

export function HandleHome() {
  return window['go']['main']['App']['HandleHome']();
}
